#define __STDC_FORMAT_MACROS
#include <inttypes.h>
#define __STDINT_LIMITS
#include <stdint.h>
#include "hwacha.h"
#include "decode_hwacha.h"
#include "encodings_hwacha.h"
#include "rocc.h"
#include <assert.h>
